### ISSUE TITLE
Bug /proc/0/stat: not found

### ISSUE THREAD

**Issue by Raynor999** [seiginonakama/BlockCanaryEx#12]
doSample: 
                                                                            java.io.FileNotFoundException: /proc/0/stat: open failed: ENOENT (No such file or directory)
                                                                                at libcore.io.IoBridge.open(IoBridge.java:456)
                                                                                at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                                                                at java.io.FileInputStream.<init>(FileInputStream.java:103)
                                                                                at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.CpuSampler.doSample(CpuSampler.java:116)
                                                                                at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.CpuSampler.recordSample(CpuSampler.java:66)
                                                                                at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.BlockSamplerService$1.getCurrentCpuInfo(BlockSamplerService.java:45)
                                                                                at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.ISamplerService$Stub.onTransact(ISamplerService.java:63)
                                                                                at android.os.Binder.execTransact(Binder.java:446)
                                                                             Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                                at libcore.io.Posix.open(Native Method)
                                                                                at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                                at libcore.io.IoBridge.open(IoBridge.java:442)
                                                                                at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                                                                at java.io.FileInputStream.<init>(FileInputStream.java:103) 
                                                                                at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.CpuSampler.doSample(CpuSampler.java:116) 
                                                                                at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.CpuSampler.recordSample(CpuSampler.java:66) 
                                                                                at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.BlockSamplerService$1.getCurrentCpuInfo(BlockSamplerService.java:45) 
                                                                                at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.ISamplerService$Stub.onTransact(ISamplerService.java:63) 
                                                                                at android.os.Binder.execTransact(Binder.java:446)

**Comment by AlexTereschuk** [comment]
Hi!
Have the same issue on Genymotion Android API 21:
`java.io.FileNotFoundException: /proc/0/stat: open failed: ENOENT (No such file or directory)
                                                 at libcore.io.IoBridge.open(IoBridge.java:456)
                                                 at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                                 at java.io.FileInputStream.<init>(FileInputStream.java:103)
                                                 at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.CpuSampler.doSample(CpuSampler.java:116)
                                                 at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.CpuSampler.recordSample(CpuSampler.java:66)
                                                 at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.BlockSamplerService$1.getCurrentCpuInfo(BlockSamplerService.java:47)
                                                 at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.ISamplerService$Stub.onTransact(ISamplerService.java:63)
                                                 at android.os.Binder.execTransact(Binder.java:446)
                                              Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                 at libcore.io.Posix.open(Native Method)
                                                 at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                 at libcore.io.IoBridge.open(IoBridge.java:442)
                                                 at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                                 at java.io.FileInputStream.<init>(FileInputStream.java:103) 
                                                 at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.CpuSampler.doSample(CpuSampler.java:116) 
                                                 at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.CpuSampler.recordSample(CpuSampler.java:66) 
                                                 at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.BlockSamplerService$1.getCurrentCpuInfo(BlockSamplerService.java:47) 
                                                 at com.letv.sarrsdesktop.blockcanaryex.jrt.internal.ISamplerService$Stub.onTransact(ISamplerService.java:63) 
                                                 at android.os.Binder.execTransact(Binder.java:446) `
