### ISSUE TITLE
添加依赖后项目无法编译通过

### ISSUE THREAD

**Issue by nuoxiang** [seiginonakama/BlockCanaryEx#14]
```java
Caused by: com.android.build.gradle.tasks.ResourceException: Error: java.lang.RuntimeException: java.io.EOFException: End of input at line 6277 column 17 path $[0].map[316].from.position.endOffset
	at com.android.build.gradle.tasks.MergeResources.doFullTaskAction(MergeResources.java:166)
	at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:88)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 78 more
Caused by: Error: java.lang.RuntimeException: java.io.EOFException: End of input at line 6277 column 17 path $[0].map[316].from.position.endOffset
	at com.android.ide.common.res2.MergedResourceWriter.postWriteAction(MergedResourceWriter.java:531)
	at com.android.ide.common.res2.MergeWriter.end(MergeWriter.java:48)
	at com.android.ide.common.res2.MergedResourceWriter.end(MergedResourceWriter.java:220)
	at com.android.ide.common.res2.DataMerger.mergeData(DataMerger.java:301)
	at com.android.ide.common.res2.ResourceMerger.mergeData(ResourceMerger.java:410)
	at com.android.build.gradle.tasks.MergeResources.doFullTaskAction(MergeResources.java:159)
	... 85 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.io.EOFException: End of input at line 6277 column 17 path $[0].map[316].from.position.endOffset
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at com.android.ide.common.blame.MergingLog.getMergedFileMap(MergingLog.java:140)
	at com.android.ide.common.blame.MergingLog.logSource(MergingLog.java:121)
	at com.android.ide.common.res2.MergedResourceWriter.postWriteAction(MergedResourceWriter.java:483)
	... 90 more
Caused by: java.lang.RuntimeException: java.io.EOFException: End of input at line 6277 column 17 path $[0].map[316].from.position.endOffset
	at com.android.ide.common.blame.MergingLogPersistUtil.loadFromMultiFile(MergingLogPersistUtil.java:204)
	at com.android.ide.common.blame.MergingLog$2.load(MergingLog.java:70)
	at com.android.ide.common.blame.MergingLog$2.load(MergingLog.java:66)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	... 96 more
Caused by: java.io.EOFException: End of input at line 6277 column 17 path $[0].map[316].from.position.endOffset
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:482)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
	at com.android.ide.common.blame.SourcePositionJsonTypeAdapter.read(SourcePositionJsonTypeAdapter.java:74)
	at com.android.ide.common.blame.SourceFilePositionJsonSerializer.read(SourceFilePositionJsonSerializer.java:56)
	at com.android.ide.common.blame.MergingLogPersistUtil.loadFromMultiFile(MergingLogPersistUtil.java:178)
	... 102 more



```

以上是gradle报错信息

**Comment by seiginonakama** [comment]
请问一下您的com.android.tools.build:gradle:版本是多少？

**Comment by nuoxiang** [comment]
2.3.2
