### ISSUE TITLE
After upgrade Android gradle plugin to 3.0.0, apply plugin blockcanaryex failed.

### ISSUE THREAD

**Issue by qinjunli** [seiginonakama/BlockCanaryEx#19]
> Caused by: java.lang.ExceptionInInitializerError
	at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:56)
	at org.gradle.api.internal.plugins.DefaultPluginManager.instantiatePlugin(DefaultPluginManager.java:72)
	... 113 more
Caused by: groovy.lang.MissingMethodException: No signature of method: org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.DefaultVersionComparator.asStringComparator() is applicable for argument types: () values: []
Possible solutions: asVersionComparator()
	at com.letv.sarrsdesktop.blockcanaryex.BlockCanaryExPlugin.<clinit>(BlockCanaryExPlugin.groovy:42)
	... 115 more

Environment:

1. Android studio 3.0
2. Android gradle plugin 3.0.0-alpha6
3. BlockCanaryExPlugin 0.9.9.2

**Comment by SaeedMasoumi** [comment]
Same issue

**Comment by xihuxiaolongren** [comment]
Same issue

**Comment by seiginonakama** [comment]
fixed in BlockCanaryExPlugin 0.9.9.4.

```groovy
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0' //version must >= 1.5.0
        classpath 'com.letv.sarrsdesktop:BlockCanaryExPlugin:0.9.9.4'
    }
}
```

@qinjunli @SaeedMasoumi @xihuxiaolongren you can have a try.

**Comment by SaeedMasoumi** [comment]
@seiginonakama I've got the following error after using the newer version

```
Execution failed for task ':presentation:transformClassesWithBlockCanaryExForMockDebug'.
> No signature of method: java.lang.String.getName() is applicable for argument types: () values: []
  Possible solutions: getAt(groovy.lang.EmptyRange), getAt(java.lang.String), getAt(int), getAt(int), getAt(groovy.lang.Range), getAt(groovy.lang.IntRange)

```

**Comment by seiginonakama** [comment]
@SaeedMasoumi fixed in BlockCanaryExPlugin 0.9.9.5。（fxxk tpye-unsafe）
